#!/usr/bin/env php
<?php
use Puddle\Commands\AddCommand;
use Puddle\Commands\DeleteCommand;
use Puddle\Config;
use Puddle\Console;

require_once __DIR__ . '/vendor/autoload.php';

$Config = Config::load(file: __DIR__ . '/../blog.json');
$Console = new Console(config: $Config);
$Console->addCommand(command: new AddCommand(name: 'add', config: $Config));
$Console->addCommand(command: new DeleteCommand(name: 'delete', config: $Config));
$Console->run();
